version: 2

models:

  - name: dim_customers
    description: Customer dimension table

    columns:

      - name: customer_id
        description: Unique customer identifier

        tests:
          - unique
          - not_null

      - name: email
        tests:
          - not_null

  - name: dim_products
    description: Product dimension table

    columns:

      - name: product_id

        tests:
          - unique
          - not_null

  - name: fact_orders
    description: Order fact table

    columns:

      - name: customer_id

        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id

      - name: product_id

        tests:
          - relationships:
              to: ref('dim_products')
              field: product_id